import type { Metadata } from "next";
import Header from "@/components/sections/header";
import Footer from "@/components/sections/footer";

export const metadata: Metadata = {
  title: "Privacy Policy — ChatGPT++",
  description: "Privacy Policy for the ChatGPT++ Chrome Extension.",
};

const sections = [
  {
    title: "Overview",
    content:
      "ChatGPT++ is a Chrome extension that enhances the ChatGPT interface. It operates entirely within your browser. No data is collected, transmitted, or shared with any external server or third party.",
  },
  {
    title: "Data Collection",
    content: "ChatGPT++ does not collect any personal data. Specifically:",
    list: [
      "No analytics or telemetry",
      "No cookies set by the extension",
      "No external network requests",
      "No user behavior tracking",
      "No advertising identifiers",
    ],
  },
  {
    title: "Data Storage",
    content:
      "All data generated by the extension (such as user preferences, hidden chat IDs, and vault configuration) is stored exclusively in Chrome's local and sync storage APIs. This data remains on your device and within your Chrome profile.",
    after:
      "The extension does not access, store, or transmit the contents of your conversations outside of your browser.",
  },
  {
    title: "Vault & PIN Security",
    content:
      "The Secure Chat Lock feature allows users to protect conversations with a PIN. The PIN is hashed using SHA-256 before storage. The original PIN is never stored in plaintext. All vault operations occur client-side.",
  },
  {
    title: "Permissions",
    content: "The extension requires the following Chrome permissions:",
    list: [
      "activeTab — to interact with the ChatGPT interface on the current tab",
      "scripting — to inject the content script into ChatGPT pages",
      "webRequest — to capture authentication headers for API calls to chatgpt.com",
      "storage — to persist user preferences and vault data locally",
      "tabs — to scope the extension icon to ChatGPT tabs only",
    ],
    after:
      "No additional permissions are requested. Host permissions are limited to chatgpt.com and its subdomains.",
  },
  {
    title: "Third-Party Services",
    content:
      "ChatGPT++ does not integrate with, send data to, or receive data from any third-party service, API, or server. All authenticated API calls are made directly to chatgpt.com/backend-api using the same headers that ChatGPT itself uses.",
  },
  {
    title: "Open Source",
    content:
      "The extension source code is publicly available for audit. Users are encouraged to review the codebase to verify these privacy claims.",
  },
  {
    title: "Changes to This Policy",
    content:
      "If this policy is updated, the effective date at the top of this page will be revised. Continued use of the extension after changes constitutes acceptance of the updated policy.",
  },
  {
    title: "Contact",
    content:
      "For questions about this privacy policy, open an issue on the project's GitHub repository.",
  },
];

export default function PrivacyPage() {
  return (
    <>
      <Header />
      <main className="pt-32 pb-24">
        <div className="mx-auto max-w-[760px] px-6">
          <a
            href="/"
            className="text-sm text-[#A1A1AA] hover:text-white transition-colors duration-200 mb-12 inline-block"
          >
            &larr; Back to Home
          </a>

          <h1 className="text-[clamp(36px,5vw,56px)] font-extrabold tracking-[-0.04em] leading-[1.05] mb-4">
            Privacy Policy
          </h1>
          <p className="text-sm text-[#666666] mb-16">
            Effective date: March 4, 2026
          </p>

          {sections.map((section) => (
            <div key={section.title} className="mb-12">
              <h2 className="text-xl font-bold tracking-[-0.3px] mb-4">
                {section.title}
              </h2>
              <p className="text-[16px] text-[#A1A1AA] leading-[1.75] mb-4">
                {section.content}
              </p>
              {section.list && (
                <ul className="space-y-2 mb-4">
                  {section.list.map((item) => (
                    <li
                      key={item}
                      className="text-[16px] text-[#A1A1AA] leading-[1.75] pl-5 relative before:content-['—'] before:absolute before:left-0 before:text-white"
                    >
                      {item}
                    </li>
                  ))}
                </ul>
              )}
              {section.after && (
                <p className="text-[16px] text-[#A1A1AA] leading-[1.75]">
                  {section.after}
                </p>
              )}
            </div>
          ))}

          {/* Trademark Disclaimer */}
          <div className="mt-20 pt-8 border-t border-[rgba(255,255,255,0.08)]">
            <h2 className="text-sm font-semibold text-[#666666] mb-3">
              Trademark Disclaimer
            </h2>
            <p className="text-xs text-[#666666] leading-relaxed">
              ChatGPT is a trademark of OpenAI, Inc. This extension is not
              created by, affiliated with, endorsed by, or sponsored by OpenAI.
              All product names, trademarks, and registered trademarks are the
              property of their respective owners.
            </p>
          </div>
        </div>
      </main>
      <Footer />
    </>
  );
}
